User.create!([
  {phone: nil, email: "test@mail.com", password: "tester", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-04-12 13:01:07", last_sign_in_at: "2017-04-04 23:15:57", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", confirmation_token: "hSHTzhhS97RTeM_9sFaK", confirmed_at: "2017-04-04 23:15:47", confirmation_sent_at: "2017-04-04 23:15:44", unconfirmed_email: nil, failed_attempts: 0, unlock_token: nil, locked_at: nil, type: nil, username: "test", first_name: nil, last_name: nil, birthday: nil, city: nil},
  {phone: nil, email: "xs290@me.com", password: "tester", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2017-04-12 12:46:48", last_sign_in_at: "2017-04-04 20:57:21", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", confirmation_token: "PdYQWTDopvQ2pxnQPcx6", confirmed_at: "2017-04-04 19:59:47", confirmation_sent_at: "2017-04-04 19:59:34", unconfirmed_email: nil, failed_attempts: 1, unlock_token: nil, locked_at: nil, type: nil, username: "khmelevskoy_s", first_name: nil, last_name: nil, birthday: nil, city: nil},
  {phone: nil, email: "test@me.com", password: "tester", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, confirmation_token: "t6Anb7Dnt-zVRL-y56G-", confirmed_at: "2017-04-12 15:05:17", confirmation_sent_at: "2017-04-12 15:05:13", unconfirmed_email: nil, failed_attempts: 0, unlock_token: nil, locked_at: nil, type: nil, username: "manager", first_name: nil, last_name: nil, birthday: nil, city: nil}
])
AdminUser.create!([
  {email: "admin@example.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2017-04-12 15:11:20", last_sign_in_at: "2017-04-04 22:23:57", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}
])
Category.create!([
  {name: "Food", icon: "ico-cat-food", color: ""},
  {name: "Home and Living", icon: "ico-cat-home", color: "color3"},
  {name: "Accessories", icon: "ico-cat-accesories", color: "color2"},
  {name: "Clothes", icon: "ico-cat-clothes", color: "color4"},
  {name: "Wedding and Parties", icon: "ico-cat-wedding", color: "color3"},
  {name: "Photography", icon: "ico-cat-photo", color: ""},
  {name: "Children", icon: "ico-cat-child", color: "color4"},
  {name: "Health and Beauty", icon: "ico-cat-health", color: "color2"},
  {name: "Cars", icon: "ico-cat-cars", color: "color3"}
])
Page.create!([
  {title: "Terms and conditions", content: "<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and g<strong>oing through the cites o</strong>f the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by</p>\r\n<p>&nbsp;</p>\r\n<p>Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"},
  {title: "FAQ", content: "<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>"},
  {title: "Contact us", content: "<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>"},
  {title: "About us", content: "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>\r\n\r\n<h2>Why do we use it?</h2>\r\n<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>\r\n\r\n\r\n<h2>Where does it come from?</h2>\r\n<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.</p>\r\n\r\n<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"}
])
Shop.create!([
  {title: "Fashion shop Khmelevskoy", image: "1.png", description: "My shop provide ultimate goods to the consumers around the world. ", location: "Helsinki, Finland", email: "xs290@me.com", phone: "0466461777", phone_2: "0466461222", contacts: "Contact me in t.me/khmelevskoy_s", slug: "fashion-shop-khmelevskoy", user_id: 1, category_id: 4, latitude: 60.1698557, longitude: 24.938379},
  {title: "Autotrader", image: "48d2c804d0d6cdf1-main.jpg", description: "<p><span style=\"color: #262626; font-family: arial, helvetica, sans-serif; font-size: 13px;\">Only a few brands shape the way of life as MINI. A MINI leaves a statement. MINI drivers are dynamic, determined and style-conscious. Whether for leisure time or business. Discover the benefits you enjoy as a MINI corporate customer. And you get an idea of how fascinating an everyday business life with a MINI as a company car can be.</span></p>", location: "Canada, Quebec", email: "my@mail.com", phone: "88949232422", phone_2: "42422342211", contacts: "", slug: "autotrader", user_id: 2, category_id: 9, latitude: 46.8138783, longitude: -71.2079809},
  {title: "H&M toronto", image: "ThinkstockPhotos-458598915.jpg", description: "<p>The scramble for retail space in South Africa will intensify when Swedish company Hennes &amp; Mauritz launches in the country next month.H&amp;M will lease a multilevel 4700m&sup2; location at the V&amp;A Waterfront in Cape Town, its first store in Africa.Property developers are being forced to create more space to accommodate high demand from global...</p>", location: "CF Toronto Eaton Centre, 1 Dundas St W ", email: "hm@hm.com", phone: "+1 855-272-7007", phone_2: "", contacts: "", slug: "h-m-toronto", user_id: 2, category_id: 4, latitude: 43.6554038, longitude: -79.3819289}
])
